const { Schema, model } = require('mongoose');

/**
 * Post (or Comment) document shape
 * ───────────────────────────────
 *  _id         ObjectId  – autogenerated
 *  post_id     ObjectId  – the parent post (omit if this **is** the post)
 *  user_id     String    – or ObjectId if you have a Users collection
 *  content     String    – text body
 *  type        String    – e.g. "news" | "opinion" | "question"…
 *  created_at  Date      – filled automatically
 *  updated_at  Date      – filled automatically
 */
const PostSchema = new Schema(
  {
    post_id: {
      type: Schema.Types.ObjectId,
      ref : 'Post',
      required: false, //This causes an error if try to create a top-level post bc it doesn't have a post_id
    },
    user_id: {
      type: String,                 // change to Schema.Types.ObjectId if you store users
      required: true,
    },
    content: {
      type: String,
      required: true,
      trim: true,
    },
    image_url: {
      type: String,
      required: false
    },
    type: {
      type: String,
      enum: ['news', 'poll', 'event'],
      default: 'news',
    },
  },
  {
    timestamps: { createdAt: 'created_at', updatedAt: 'updated_at' },
    collection: 'Posts',
  }
);

module.exports = model('Post', PostSchema);
