const { Schema, model } = require('mongoose');

/**
 * User document shape
 * ───────────────────────────────
 * user_id     ObjectId  – autogenerated
 * role_id     ObjectId  – role id
 * * username    String    – username
 * * password    String    – password
 * * email       String    – email
 * * neighbourhood String    – neighbourhood
 */
const UserSchema = new Schema(
{
    role_id: {
      type: String,
      ref : 'Role',
      required: true,
    },
    username: {
      type: String,
      required: true,
      trim: true,
    }, 
    password: {
      type: String,
      required: true,
      trim: true,
    },
    email: {
      type: String,
      required: true,
      trim: true,
    },
    neighbourhood: {
      type: String,
      required: true,
      trim: true,
    },
    profilePic: {
      type: String, 
      default: '/uploads/default.jpg', 
    },
},
  {
    timestamps: { createdAt: 'created_at', updatedAt: 'updated_at' },
    collection: 'Users',
  }
);

module.exports = model('User', UserSchema);
