const { Schema, model } = require('mongoose');

/**
 * User document shape
 * ───────────────────────────────
 * user_id     ObjectId  – autogenerated
 * * username    String    – username
 * * password    String    – password
 * * email       String    – email
 * * neighbourhood String    – neighbourhood
 * location: {             - GeoJSON point
 *  type         String    - JSON type of 'Point"
 *  coordinates [Number]   - [long, lat]
 * }
 */
const UserSchema = new Schema(
{
    username: {
      type: String,
      required: true,
      trim: true,
    }, 
    password: {
      type: String,
      required: true,
      trim: true,
    },
    email: {
      type: String,
      required: true,
      trim: true,
    },
    neighbourhood: {
      type: String,
      required: true,
      trim: true,
    },
    location: {
      type: {
        type: String,
        enum: ['Point'],
        default: 'Point',
        required: true
      },
      coordinates: {
        type: [Number],
        default: [0,0],
        required: true
      }
    },
    profilePic: {
      type: String, 
      default: '/uploads/default.jpg', 
    },
},
  {
    timestamps: { createdAt: 'created_at', updatedAt: 'updated_at' },
    collection: 'Users',
  }
);

//Defining a geospatial index for queries and maps
UserSchema.index({ location: '2dsphere' });

module.exports = model('User', UserSchema);
